# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Kian Ahrabian
title: Kian Ahrabian
email: kian.ahrabian@mail.mcgill.ca
description: >
  Personal webpage of Kian Ahrabian. Based on [al-folio](https://github.com/alshedivat/al-folio) design.
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: https://www.cs.mcgill.ca/~kahrab/
baseurl: ''
last_updated: 16 Jan 2019

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: kahrabian
twitter_username: kahrabian
linkedin_username: kahrabian
scholar_userid: pwUdiCYAAAAJ
orcid_id: 0000-0002-6606-9735
contact_note:

google_analytics: UA-105929253-1

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: It's a geeky life
blog_description: a grad student in a country far far away ...

# Pagination
paginate: 5
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname:

# Optional features
show_social_icons: true
enable_anchorjs: true
enable_katex: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll/scholar
  - jemoji

# Jekyll-Scholar
scholar:
  last_name: Ahrabian

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
